-- Create files at OUTBOUND_DP server 1

CREATE TABLE  INBOUND.E$PT_PROMO_ITEM_FCT_0802 ORGANIZATION EXTERNAL
 ( TYPE oracle_datapump DEFAULT DIRECTORY  OUTBOUND_DP ACCESS PARAMETERS ( COMPRESSION ENABLED )
 ( TYPE oracle_datapump DEFAULT DIRECTORY  OUTBOUND_DP ACCESS PARAMETERS ( COMPRESSION ENABLED )
 LOCATION  ( 'PT_PROMO_ITEM_FCT_0802_1.dmp' , 'PT_PROMO_ITEM_FCT_0802_2.dmp' , 'PT_PROMO_ITEM_FCT_0802_3.dmp' )) AS
    SELECT /*+ PARALLEL(TGT,3) */ * from WAREHOUSE_BUILD.PT_PROMO_ITEM_FCT_0802 TGT ;


-- rsync --verbose  --progress --stats --recursive --times PT_PROMO_ITEM_FCT_0804.dmp server2:path to files

-- Create ET table on different server

CREATE TABLE "WAREHOUSE_BUILD"."PT_PROMO_ITEM_FCT_0802"
   (    "PROMO_ITEM_FID" NUMBER(*,0),
        "PROMO_ID" NUMBER(*,0),
        "DATE_ID" DATE,
        "TIME_START_ID" NUMBER(*,0),
        "TIME_END_ID" NUMBER(*,0),
        "PROD_ID" NUMBER(*,0),
        "PROD_HIST_ID" NUMBER(*,0),
        "STORE_ID" NUMBER(*,0),
        "STORE_HIST_ID" NUMBER(*,0),
        "OFFER_ID" NUMBER(*,0),
        "PROMO_CYCLE_ID" NUMBER(*,0),
        "PROMO_DISPLAY_ID" NUMBER(*,0),
        "PROMO_FLYER_ID" NUMBER(*,0),
        "TRIGGER_FLAG" CHAR(1 CHAR),
        "REWARD_FLAG" CHAR(1 CHAR),
        "LOAD_ID" NUMBER(*,0),
        "CREATED_DTTM" DATE,
        "MODIFIED_DTTM" DATE
   )
   ORGANIZATION EXTERNAL
    ( TYPE ORACLE_DATAPUMP
      DEFAULT DIRECTORY "OUTBOUND_DP"
      ACCESS PARAMETERS
      ( COMPRESSION ENABLED     )
      LOCATION
       ( 'PT_PROMO_ITEM_FCT_0802_1.dmp', 'PT_PROMO_ITEM_FCT_0802_2.dmp', 'PT_PROMO_ITEM_FCT_0802_3.dmp' )
       );
